cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - node
  - npm
  - typescript
language: en,eo,ja
languageSettings:
  - allowCompoundWords: true
    caseSensitive: false
    enabled: true
    languageId: '*'
    locale: en,ja
ignorePaths:
  - .*rc.*
  - .git/objects
  - .github/CODE_OF_CONDUCT.*
  - .vscode
  - .yarn
  - cspell.config.yml
  - node_modules
  - yarn.lock
ignoreWords:
  - kito
  - kurone
  - Kuron√©
  - tsbuildinfo
  - nextjs
useGitignore: true
version: '0.2'
